### ISSUE TITLE
Structure du dictionnaire

### ISSUE THREAD

**Issue by apagliai** [AnthonyP06/super_encryptator_4MIN12#1]
Pour le dictionnaire (généré par le programme 'key_encryptator') j'avais pensé définir une nouvelle structure : 

---

struct dictionnaire 
{
  // La clé, ça peut être bien de la garder sous le coude.
  char\* key;

  // Le dictionnaire des caractères ASCII, dans l'ordre alphabétique (ordre ASCII)
  char regular_dict[94];       // 94 : 126-33+1, c'est le nombre de caractères qu'on doit pouvoir traiter

  // Le dictionnaire crypté
  char encr_dict[94];
};

typedef struct dictionnaire dictionnaire_t; 

---

Qu'en penses-tu ?

**Comment by ColinMourard** [comment]
Oui c'est à peu près la structure à laquelle j'avais pensé.
Mais est-ce qu'on est obligé de réécrire tout le dictionnaire ASCII? Je pense qu'on peut y accéder directement sans le "char regular_dict[94];..."

**Comment by apagliai** [comment]
@ColinMourard (Je crois qu'en te taguant avec l'@ tu vas être notifié ...)
A priori ouais tu as raison c'est pas forcément utile d'avoir tout le dictionnaire ASCII. Mais pour 94o de mémoire, tu penses pas que ça nous simplifierait le travail ?
Pour faire correspondre les deux dictionnaires on aura pas à ce casser la tête à chaque fois pour convertir ...

**Comment by ColinMourard** [comment]
@AnthonyP06 Je suis notifié dans les deux cas, t'inquiètes!

C'est vrai qu'au final, c'est pas ce qui va ralentir le prog donc pourquoi pas. Je regarde un peu cet aprème.

**Comment by apagliai** [comment]
@ColinMourard 
Ok, je suis parti sur ça aussi du coup (cf mon commit). J'ai juste rajouté le caractère ASCII '32' puisque c'est l'espace. 
Je ferme l'issue !
